excludes:
  paths:
  - pattern: "cpp/test"
    reason : "TEST_TOOL_OF"
    comment: "Directory containing code only used for testing. Not included in released artifacts in the context of this project."
  - pattern: "golang/*_test.go"
    reason : "TEST_TOOL_OF"
    comment: "Files containing code only used for testing. Not included in released artifacts in the context of this project."
  - pattern: "python/test_flexpolyline.py"
    reason : "TEST_TOOL_OF"
    comment: "File containing code only used for testing. Not included in released artifacts in the context of this project."
  - pattern: "test"
    reason : "TEST_TOOL_OF"
    comment: "Directory containing code only used for testing. Not included in released artifacts in the context of this project."
  scopes:
  - pattern   : "dev-dependencies"
    reason : "DEV_DEPENDENCY_OF"
    comment: "Scope with dependencies only used for development. Not included in released artifacts in the context of this project."
  - pattern   : "devDependencies"
    reason : "DEV_DEPENDENCY_OF"
    comment: "Scope with dependencies only used for development. Not included in released artifacts in the context of this project."