name: flexible_polyline
description: >-
    Flexible Polyline encoder and decoder for representing a list of GPS
    coordinates (and optional elevation) into a compressed URL-safe string.
version: 1.0.1
homepage: https://github.com/heremaps/flexible-polyline
repository: https://github.com/heremaps/flexible-polyline/dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  tuple: ^2.0.0

dev_dependencies:
  test: ^1.17.5
